server:
  port: 8081
spring:
  swagger:
    enable: true
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    mongodb:
      uri: mongodb://im:byc123@47.105.209.57:27017/im
websocket:
  port: 1234
  address: ws://localhost:${websocket.port}/websocket
